import React from 'react';

export default function Disclaimer() {
  return (
    <div className="mx-auto max-w-[850px] px-4 sm:px-6 py-16 flex flex-col gap-12 select-none text-center sm:text-left">
      
      {/* Header */}
      <section className="flex flex-col gap-3 border-b border-border-subtle pb-8">
        <span className="text-xs uppercase tracking-[0.15em] text-muted">
          Legal Framework & Scope
        </span>
        <h1 className="text-4xl sm:text-5xl font-light tracking-tight text-white font-serif">
          Disclaimer
        </h1>
        <p className="text-base sm:text-lg text-secondary-text font-light leading-relaxed max-w-xl">
          Important information about the StatFin AI analysis and its limitations.
        </p>
      </section>

      {/* Main Info Card */}
      <section className="rounded-xl border border-border-subtle bg-dark-surface p-8 sm:p-10 flex flex-col gap-6 text-left shadow-2xl">
        <h2 className="text-sm font-semibold uppercase tracking-widest text-white border-b border-border-subtle pb-3">
          Important Disclaimer
        </h2>

        <div className="flex flex-col gap-5 text-xs sm:text-sm text-secondary-text leading-relaxed font-light font-sans">
          <p className="font-semibold text-white">
            StatFin AI is an educational statistical analysis prototype. The Prototype Risk Score is a
            project-specific analytical indicator and has not been financially validated.
          </p>

          <p>
            This application does not provide professional financial, investment, lending, insurance, or
            tax advice.
          </p>

          <p>
            The results generated by StatFin AI are based on the financial information provided by the user
            and the statistical methods implemented within the application. They are intended for
            educational and informational purposes only.
          </p>

          <p>
            The Prototype Risk Score should not be interpreted as a standardized or professionally
            validated financial risk score.
          </p>

          <p>
            Users should not rely solely on StatFin AI when making significant financial decisions. We recommend
            consulting a certified financial planner for tax filing, loan approvals, or asset allocations.
          </p>
        </div>
      </section>

      {/* Signature block */}
      <section className="border-t border-border-subtle pt-8 text-center sm:text-left">
        <p className="font-serif text-sm font-semibold text-white">StatFin AI</p>
        <p className="text-xs text-muted italic mt-0.5 font-serif">
          Statistical Intelligence for Smarter Financial Decisions.
        </p>
      </section>
    </div>
  );
}
